apps/the_score_web/lib/the_score_web/router.ex
defmodule TheScoreWeb.Router do
  use TheScoreWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TheScoreWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TheScoreWeb do
    pipe_through :browser

    live "/", RushingLive.Index, :index
    live "/rushing", RushingLive.Index, :index
    get "/download/rushing_statistics", DownloadController, :rushing_stats
  end

  # Other scopes may use custom stacks.
  # scope "/api", TheScoreWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TheScoreWeb.Telemetry
    end
  end
end

apps/the_score_web/lib/the_score_web/live/live_helpers.ex
defmodule TheScoreWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `TheScoreWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, TheScoreWeb.RushingLive.FormComponent,
        id: @rushing.id || :new,
        action: @live_action,
        rushing: @rushing,
        return_to: Routes.rushing_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, TheScoreWeb.ModalComponent, modal_opts)
  end
end

apps/the_score_web/lib/the_score_web/live/modal_component.ex
defmodule TheScoreWeb.ModalComponent do
  use TheScoreWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

apps/the_score_web/lib/the_score_web/live/page_live.ex
defmodule TheScoreWeb.PageLive do
  use TheScoreWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not TheScoreWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

apps/the_score_web/lib/the_score_web/live/rushing_live/form_component.ex
defmodule TheScoreWeb.RushingLive.FormComponent do
  use TheScoreWeb, :live_component

  alias TheScore.Statistics

  @impl true
  def update(%{rushing: rushing} = assigns, socket) do
    changeset = Statistics.change_rushing(rushing)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"rushing" => rushing_params}, socket) do
    changeset =
      socket.assigns.rushing
      |> Statistics.change_rushing(rushing_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"rushing" => rushing_params}, socket) do
    save_rushing(socket, socket.assigns.action, rushing_params)
  end

  defp save_rushing(socket, :edit, rushing_params) do
    case Statistics.update_rushing(socket.assigns.rushing, rushing_params) do
      {:ok, _rushing} ->
        {:noreply,
         socket
         |> put_flash(:info, "Rushing updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_rushing(socket, :new, rushing_params) do
    case Statistics.create_rushing(rushing_params) do
      {:ok, _rushing} ->
        {:noreply,
         socket
         |> put_flash(:info, "Rushing created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

apps/the_score_web/lib/the_score_web/live/rushing_live/index.ex
defmodule TheScoreWeb.RushingLive.Index do
  use TheScoreWeb, :live_view
  import TheScoreWeb.RushingView

  alias TheScore.Statistics
  alias TheScore.Statistics.Rushing

  @type direction() :: :asc | :desc
  @type sorting() :: {direction(), Rushing.field()}

  @impl true
  def mount(_params, _session, socket) do
    default_sorting = {:asc, :player_name}

    socket =
      socket
      |> assign(:sorting, default_sorting)
      |> assign(:rushing_collection, list_rushing(socket))

    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Rushing")
    |> assign(:rushing, Statistics.get_rushing!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Rushing")
    |> assign(:rushing, %Rushing{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Rushing")
    |> assign(:rushing, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    rushing = Statistics.get_rushing!(id)
    {:ok, _} = Statistics.delete_rushing(rushing)

    {:noreply, assign(socket, :rushing_collection, list_rushing(socket))}
  end

  @doc """
  Event handler to load the rushing data into the database from the 
  json file.
  """
  @impl true
  def handle_event("load_rushing_data", _, socket) do
    "#{System.cwd!()}/apps/the_score/data/rushing.json"
    |> TheScore.Database.Rushing.load_rushing_statistics_from_json_file()

    {:noreply, socket}
  end

  @doc """
  """
  @impl true
  def handle_event("name-filter", %{"name_filter_form" => %{"name" => name}}, socket) do
    socket = assign(socket, :name_filter, name)
    rushing_collection = list_rushing(socket)

    {:noreply, assign(socket, :rushing_collection, rushing_collection)}
  end

  @doc """
  Event handler for rushing table sorting by headers.
  """
  @impl true
  def handle_event("rushing-sort-by", params, socket) do
    sorting = sorting_from_params(params, socket)

    socket =
      socket
      |> assign(:rushing_collection, list_rushing(socket))
      |> assign(:sorting, sorting)

    {:noreply, socket}
  end

  @spec list_rushing(%Phoenix.LiveView.Socket{}) :: [%Rushing{}]
  defp list_rushing(socket) do
    sorting = Map.get(socket.assigns, :sorting)
    name_filter = Map.get(socket.assigns, :name_filter)
    
    Statistics.list_rushing(sorting, name_filter)
  end

  @doc """
  Figures out what sorting to use by the existing sorting in the socket and the
  desired sorting from params.
  """
  defp sorting_from_params(%{"field" => field} = _params, socket) do
    {direction, sorting_field} = socket.assigns.sorting
    field = String.to_atom(field)

    if field == sorting_field do
      {swap_direction(direction), field}
    else
      {:asc, field}
    end
  end

  defp swap_direction(:asc), do: :desc
  defp swap_direction(:desc), do: :asc
end

apps/the_score_web/lib/the_score_web/live/rushing_live/show.ex
defmodule TheScoreWeb.RushingLive.Show do
  use TheScoreWeb, :live_view

  alias TheScore.Statistics

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:rushing, Statistics.get_rushing!(id))}
  end

  defp page_title(:show), do: "Show Rushing"
  defp page_title(:edit), do: "Edit Rushing"
end

apps/the_score_web/lib/the_score_web/live/rushing_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "rushing-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :player_name %>
  <%= text_input f, :player_name %>
  <%= error_tag f, :player_name %>

  <%= label f, :team_abbr %>
  <%= text_input f, :team_abbr %>
  <%= error_tag f, :team_abbr %>

  <%= label f, :position %>
  <%= text_input f, :position %>
  <%= error_tag f, :position %>

  <%= label f, :att_g %>
  <%= number_input f, :att_g, step: "any" %>
  <%= error_tag f, :att_g %>

  <%= label f, :att %>
  <%= number_input f, :att, step: "any" %>
  <%= error_tag f, :att %>

  <%= label f, :yds %>
  <%= number_input f, :yds, step: "any" %>
  <%= error_tag f, :yds %>

  <%= label f, :avg %>
  <%= number_input f, :avg, step: "any" %>
  <%= error_tag f, :avg %>

  <%= label f, :yds_g %>
  <%= number_input f, :yds_g, step: "any" %>
  <%= error_tag f, :yds_g %>

  <%= label f, :td %>
  <%= number_input f, :td, step: "any" %>
  <%= error_tag f, :td %>

  <%= label f, :lng %>
  <%= number_input f, :lng, step: "any" %>
  <%= error_tag f, :lng %>

  <%= label f, :first %>
  <%= number_input f, :first, step: "any" %>
  <%= error_tag f, :first %>

  <%= label f, :first_percent %>
  <%= number_input f, :first_percent, step: "any" %>
  <%= error_tag f, :first_percent %>

  <%= label f, :twenty %>
  <%= number_input f, :twenty, step: "any" %>
  <%= error_tag f, :twenty %>

  <%= label f, :forty %>
  <%= number_input f, :forty, step: "any" %>
  <%= error_tag f, :forty %>

  <%= label f, :fum %>
  <%= number_input f, :fum, step: "any" %>
  <%= error_tag f, :fum %>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

apps/the_score_web/lib/the_score_web/live/rushing_live/index.html.leex
<p>For convience you can load the database from the json file here!</p>
<button phx-click="load_rushing_data">Load DB (Don't do this multiple times)</button>

<hr/>

<h1>Rushing Statistics</h1>

<%= f = form_for :name_filter_form, "#", phx_submit: "name-filter" %>
<%= text_input f, :name, class: "rushing__search-name-filter", placeholder: "Filter by player name...", value: Map.get(assigns, :name_filter) %> 
  <%= submit "", style: "display:none" %>
</form>


<%= download_link(@sorting, Map.get(assigns, :name_filter)) %> 

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, TheScoreWeb.RushingLive.FormComponent,
    id: @rushing.id || :new,
    title: @page_title,
    action: @live_action,
    rushing: @rushing,
    return_to: Routes.rushing_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="player_name">Name <%= draw_sorting_direction(:player_name, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="team_abbr">Team <%= draw_sorting_direction(:team_abbr, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="position">Position<%= draw_sorting_direction(:position, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="att_g">Att/G<%= draw_sorting_direction(:att_g, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="att">Att <%= draw_sorting_direction(:att, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="yds">Yds <%= draw_sorting_direction(:yds, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="avg">Avg <%= draw_sorting_direction(:avg, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="yds_g">Yds/g <%= draw_sorting_direction(:yds_g, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="td">Td <%= draw_sorting_direction(:td, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="lng">Lng <%= draw_sorting_direction(:lng, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="first">1st <%= draw_sorting_direction(:first, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="first_percent">1st% <%= draw_sorting_direction(:first_percent, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="twenty">20+ <%= draw_sorting_direction(:twenty, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="forty">40+ <%= draw_sorting_direction(:forty, @sorting) %></th>
      <th class="rushing__tbl-header" phx-click="rushing-sort-by" phx-value-field="fum">Fum <%= draw_sorting_direction(:fum, @sorting) %></th>
    </tr>
  </thead>
  <tbody id="rushing">
    <%= for rushing <- @rushing_collection do %>
      <tr id="rushing-<%= rushing.id %>">
        <td class="rushing__tbl-value"><%= rushing.player_name %></td>
        <td class="rushing__tbl-value"><%= rushing.team_abbr %></td>
        <td class="rushing__tbl-value"><%= rushing.position %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.att_g %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.att %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.yds %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.avg %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.yds_g %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.td %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.lng %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.first %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.first_percent %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.twenty %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.forty %></td>
        <td class="rushing__tbl-value rushing__tbl-value--right"><%= rushing.fum %></td>

        <td>
          <span><%# live_redirect "Show", to: Routes.rushing_show_path(@socket, :show, rushing) %></span>
          <span><%# live_patch "Edit", to: Routes.rushing_index_path(@socket, :edit, rushing) %></span>
          <span><%# link "Delete", to: "#", phx_click: "delete", phx_value_id: rushing.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%# live_patch "New Rushing", to: Routes.rushing_index_path(@socket, :new) %></span>

apps/the_score_web/lib/the_score_web/live/rushing_live/show.html.leex
<h1>Show Rushing</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, TheScoreWeb.RushingLive.FormComponent,
    id: @rushing.id,
    title: @page_title,
    action: @live_action,
    rushing: @rushing,
    return_to: Routes.rushing_show_path(@socket, :show, @rushing) %>
<% end %>

<ul>

  <li>
    <strong>Player name:</strong>
    <%= @rushing.player_name %>
  </li>

  <li>
    <strong>Team abbr:</strong>
    <%= @rushing.team_abbr %>
  </li>

  <li>
    <strong>Position:</strong>
    <%= @rushing.position %>
  </li>

  <li>
    <strong>Att g:</strong>
    <%= @rushing.att_g %>
  </li>

  <li>
    <strong>Att:</strong>
    <%= @rushing.att %>
  </li>

  <li>
    <strong>Yds:</strong>
    <%= @rushing.yds %>
  </li>

  <li>
    <strong>Avg:</strong>
    <%= @rushing.avg %>
  </li>

  <li>
    <strong>Yds g:</strong>
    <%= @rushing.yds_g %>
  </li>

  <li>
    <strong>Td:</strong>
    <%= @rushing.td %>
  </li>

  <li>
    <strong>Lng:</strong>
    <%= @rushing.lng %>
  </li>

  <li>
    <strong>First:</strong>
    <%= @rushing.first %>
  </li>

  <li>
    <strong>First percent:</strong>
    <%= @rushing.first_percent %>
  </li>

  <li>
    <strong>Twenty:</strong>
    <%= @rushing.twenty %>
  </li>

  <li>
    <strong>Forty:</strong>
    <%= @rushing.forty %>
  </li>

  <li>
    <strong>Fum:</strong>
    <%= @rushing.fum %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.rushing_show_path(@socket, :edit, @rushing), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.rushing_index_path(@socket, :index) %></span>